trigger:
  branches:
    include:
      - main/*
  paths:
    include:
      - "ClientApp/**"
      - "ServerApp/**"

pr: none # Disable Pull Request triggern to 'default' branch, which is 'main' in this case. We only want to trigger on release branches.

variables:
  - group: infra-provision-pipeline-vars-group

stages:
  - stage: Build
    displayName: "Build Application"
    jobs:
      - job: Build_Frontend
        displayName: "Build Frontend"
        pool:
          name: "Default"
        steps:
          - checkout: self
            clean: "true"

          - task: Bash@3
            displayName: "Build Fronend Application"
            inputs:
              targetType: "inline"
              script: |
                SCRIPT_FILE=./scripts/build-frontend-app.sh
                                
                                sed -i 's/\r//g' scripts/build-frontend-app.sh

                                chmod +x $SCRIPT_FILE

                                $SCRIPT_FILE
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"

          - task: PublishPipelineArtifact@1
            displayName: "Publish Frontend Artifact to Pipeline Storage"
            inputs:
              # Point this exactly to where the build script outputs the dist folder
              targetPath: "$(System.DefaultWorkingDirectory)/terraform/dist"
              artifact: "frontend_dist_container"
              publishLocation: "pipeline"

  - stage: Deploy
    dependsOn: Build
    displayName: "Deploy Application"
    jobs:
      - job: Deploy_Frontend
        displayName: "Deploy Frontend"
        pool:
          name: "Default"
        steps:
          - checkout: self
            clean: "true"

          - task: DownloadPipelineArtifact@2
            displayName: "Download Frontend Artifact"
            inputs:
              buildType: "current"
              artifactName: "frontend_dist_container"
              # This dictates exactly where the downloaded files will land on the agent
              targetPath: "$(Pipeline.Workspace)/frontend_dist_container"

          - task: Bash@3
            displayName: "Upload Frontend Files"
            inputs:
              targetType: "inline"
              script: |
                SCRIPT_FILE=scripts/upload-frontend.sh

                sed -i 's/\r//g' scripts/upload-frontend.sh

                                chmod +x $SCRIPT_FILE

                                $SCRIPT_FILE $(TF_VAR_ENVIRONMENT) $(Pipeline.Workspace)/frontend_dist_container
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"
