export const taskStatuses = ["TODO", "IN_PROGRESS", "DONE"] as const;

export type TaskStatus = (typeof taskStatuses)[number]; // return the union of the array values, i.e. "TODO" | "IN_PROGRESS" | "DONE"

export interface Task {
  id: string;
  title: string;
  description: string;
  status: TaskStatus;
  row_version: string; // Base64-encoded string representing the row version for optimistic concurrency control
}

export interface UpdateTaskStatusPayload {
  id: string;
  status: TaskStatus;
  row_version: string; // Base64-encoded string representing the row version for optimistic concurrency control
}

export interface CreateTaskPayloadError {
  title?: string;
}

export type CreateTaskPayload = Omit<Task, "id" | "row_version">; // The payload for creating a task does not include the id or row_version, as these are generated by the backend

export type CreateUpdateTaskPayload = Omit<Task, "id"> & { id?: string };

export type UpdateTaskPayload = Task;
